services:
  db:
    image: postgres:18.4
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"
  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"
  web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    init: true

volumes:
  bundle:
  postgres_data:
